[rewrite]
# > IPA应用辅助安装器
^https:\/\/nobyda.app/(install|download) url script-analyze-echo-response https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/IPA_install/JS/IPA-Installer.js

[mitm]
hostname = %APPEND% nobyda.app
