# Name: 趣达(QuDa) 广告屏蔽与秒跳集成
# Author: Gemini
# Update: 2025-12-19

[filter]
# --- 分流模块 ---
host-keyword, kwai.com, reject
host-keyword, gdt.qq.com, reject
host-keyword, pangle.io, reject

[rewrite]
# --- 重写模块 ---
# 拦截广告调度
^https?://api\.shanghailingye\.cn/ad/map url reject-200
# 拦截配置更新
^https?://api\.shanghailingye\.cn/.*config url reject-200
# 屏蔽图片素材
^https?://pic\.fancyapi\.com/upload/ftx/creative/.* url reject-200

[mitm]
# --- 主机名解析 ---
hostname = %APPEND% api.shanghailingye.cn, pic.fancyapi.com
